//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "history_items_to_tags")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub history_item: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tag_id: i64,
    pub timestamp: Decimal,
    #[sea_orm(
        belongs_to,
        from = "history_item",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub history_items: HasOne<super::history_items::Entity>,
    #[sea_orm(
        belongs_to,
        from = "tag_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub history_tags: HasOne<super::history_tags::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
