//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "history_tags")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub r#type: i64,
    pub level: i64,
    #[sea_orm(column_type = "Text")]
    pub identifier: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    pub modification_timestamp: Decimal,
    pub item_count: i64,
    #[sea_orm(has_many)]
    pub history_items_to_tags: HasMany<super::history_items_to_tags::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
