//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "history_events")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub event_type: String,
    pub event_time: Decimal,
    #[sea_orm(column_type = "Text")]
    pub pending_listeners: String,
    #[sea_orm(column_type = "Blob", nullable)]
    pub value: Option<Vec<u8>>,
}

impl ActiveModelBehavior for ActiveModel {}
