//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "history_visits")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub history_item: i64,
    pub visit_time: Decimal,
    #[sea_orm(column_type = "Text", nullable)]
    pub title: Option<String>,
    pub load_successful: bool,
    pub http_non_get: bool,
    pub synthesized: bool,
    #[sea_orm(unique)]
    pub redirect_source: Option<i64>,
    #[sea_orm(unique)]
    pub redirect_destination: Option<i64>,
    pub origin: i64,
    pub generation: i64,
    pub attributes: i64,
    pub score: i64,
    #[sea_orm(
        belongs_to,
        from = "history_item",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub history_items: HasOne<super::history_items::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
