//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "history_items")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", unique)]
    pub url: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub domain_expansion: Option<String>,
    pub visit_count: i64,
    #[sea_orm(column_type = "Blob")]
    pub daily_visit_counts: Vec<u8>,
    #[sea_orm(column_type = "Blob", nullable)]
    pub weekly_visit_counts: Option<Vec<u8>>,
    #[sea_orm(column_type = "Blob", nullable)]
    pub autocomplete_triggers: Option<Vec<u8>>,
    pub should_recompute_derived_visit_counts: i64,
    pub visit_count_score: i64,
    pub status_code: i64,
    #[sea_orm(has_many)]
    pub history_items_to_tags: HasMany<super::history_items_to_tags::Entity>,
    #[sea_orm(has_many)]
    pub history_visits: HasMany<super::history_visits::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
