//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "history_client_versions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub client_version: i64,
    pub last_seen: Decimal,
}

impl ActiveModelBehavior for ActiveModel {}
