#![allow(dead_code)]
//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

pub mod history_client_versions;
pub mod history_event_listeners;
pub mod history_events;
pub mod history_items;
pub mod history_items_to_tags;
pub mod history_tags;
pub mod history_tombstones;
pub mod history_visits;
